trigger:
  branches:
    include:
      - master

variables:
  buildConfiguration: Release
  buildProjects: "**/*.csproj"
  packageProjects: "**/*.sfproj"

jobs:
  - job: build_old
    displayName: Build with ps script
    pool:
      vmImage: vs2017-win2016
    steps:
      - task: PowerShell@2
        displayName: "Build Code"
        inputs:
          targetType: filePath
          filePath: "./build.ps1"
  - job: cibuild
    displayName: cibuild
    pool:
      vmImage: windows-2019
    steps:
      - task: DotNetCoreInstaller@0
        displayName: Install .NET CLI
        inputs:
          version: 2.1.300
      - task: NuGetCommand@2
        displayName: Restore packages
        inputs:
          command: restore
          feedsToUse: config
          nugetConfigPath: nuget.config
          restoreSolution: "src/PatchOrchestrationApplication/packages.config"
          restoreDirectory: "../packages"
          noCache: true
          verbosityRestore: Normal
      - task: MSBuild@1
        inputs:
          solution: "src/PatchOrchestrationApplication/**/*.sfproj"
          msbuildVersion: 15.0
          msbuildArchitecture: x64
          msbuildLocation: "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/MSBuild.exe"
          platform: x64
          configuration: $(buildConfiguration)
          msbuildArguments: "/t:restore;clean;rebuild;package /nr:false /nologo"
      - task: DotNetCoreCLI@2
        displayName: Package Projects (Publish - Release)
        inputs:
          projects: $(packageProjects)
          packDirectory: $(Build.ArtifactStagingDirectory)/drop/release
          arguments: "-c $(buildConfiguration) /p:Platform=x64 /t:Package /p:PackageLocation=$(Build.ArtifactStagingDirectory)/drop/release/applicationpackage"
      - task: ServiceFabricUpdateManifests@2
        displayName: Update Service Fabric Version (Release)
        inputs:
          applicationPackagePath: $(Build.ArtifactStagingDirectory)/drop/release/applicationpackage
          versionSuffix: $(Build.BuildNumber)
          versionBehaviour: Replace
      - task: CopyFiles@2
        displayName: Copy XML Files to Artifacts (Release)
        inputs:
          SourceFolder: src\
          Contents: |
            **\*.ServiceFabric\PublishProfiles\*.xml
            **\*.ServiceFabric\ApplicationParameters\*.xml
          TargetFolder: $(Build.ArtifactStagingDirectory)/drop/release/projectartifacts
          CleanTargetFolder: true
      - task: PublishBuildArtifacts@1
        displayName: Publish Build artifacts
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)/drop
          artifactName: drop
          publishLocation: Container
